---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible device Template service.
  gather_facts: False

  tasks:
  - name: create template.
    dellemc_ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      device_id: 25123
      attributes:
        Name: "New Template"
        Description: "New Template description"

  - name: modify template
    dellemc_ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      state: "modify"
      template_id: 1234
      attributes:
        Name: "New Custom Template"
        Description: "Custom Template Description"
        Attributes:
          - Id: 1234
            Value: "Test Attribute"
            IsIgnored: false

  - name: deploy template.
    dellemc_ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      state: "deploy"
      template_id: 1234
      device_id:
        - 12345
        - 45678
      device_service_tag: ['SVTG123', 'SVTG456']
      attributes: # All options for deploy operation
        NetworkBootIsoModel:
          BootToNetwork: false
          ShareType: "NFS"
          IsoPath: "bootToIsoPath.iso"
          ShareDetail:
            IpAddress: "192.168.0.2"
            ShareName: "/nfsshare"
            User: null
            Password: null
        Attributes:
          - DeviceId: 12345
            Attributes :
              - Id : 123
                Value : "0.0.0.0"
                IsIgnored : true
        Options:
          EndHostPowerState: 1
          ShutdownType: 0
          TimeToWaitBeforeShutdown: 300
        Schedule:
          RunLater: true
          RunNow: false

