---
- hosts: hosts
  vars:
    retries_count: 5
    polling_interval: 5 #in seconds
  connection: local
  name: "OME - Update Firmware details tracking"
  gather_facts: False

  tasks:
  - name: "Update firmware from DUP file."
    dellemc_ome_firmware:
      hostname:  "{{ hostname }}"
      username: "{{ username }}"
      password:  "{{ password }}"
      device_service_tag:
        - "{{ service_tag }}"
      dup_file: "/path/Chassis-System-Management_Firmware_6N9WN_WN64_1.00.01_A00.EXE"
    register: result
    failed_when: "'update_status' not in result or 'error' in result.update_status"
      
  - name: "Get job details using job id from firmware task."
    dellemc_ome_job_facts:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      job_id: "{{result.update_status.Id}}"
    register: job_result
    failed_when: "'job_facts' not in job_result"
    until: job_result.job_facts.LastRunStatus.Name == 'Completed' or job_result.job_facts.LastRunStatus.Name == 'Failed'
    retries: "{{ retries_count }}"
    delay: "{{ polling_interval }}"
