---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible job details.
  gather_facts: False

  tasks:
  - name: Get all jobs details.
    dellemc_ome_job_facts:
      hostname:  "192.168.0.1"
      username: "username"
      password:  "password"

  - name: Get job details for id.
    dellemc_ome_job_facts:
      hostname:  "192.168.0.1"
      username: "username"
      password:  "password"
      job_id: 12345

  - name: Get filtered job details.
    dellemc_ome_job_facts:
      hostname:  "192.168.0.1"
      username: "username"
      password:  "password"
      system_query_options:
        top: 2
        skip: 1
        filter: "JobType/Id eq 8"