---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible template inventory details.
  gather_facts: False

  tasks:
    - name: Retrieve basic details of all templates.
      dellemc_ome_template_facts:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"

    - name: Retrieve details of a specific template identified by its template ID.
      dellemc_ome_template_facts:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        template_id: "{{template_id}}"