---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible device inventory details.
  gather_facts: False

  tasks:
    - name: Retrieve basic inventory of all devices.
      dellemc_ome_device_facts:
        hostname:  "192.168.0.1"
        username: "username"
        password:  "password"

    - name: Retrieve basic inventory for devices identified by IDs 33333 or 11111 using filtering.
      dellemc_ome_device_facts:
        hostname: "192.168.0.1"
        username: "username"
        password: "password"
        fact_subset: "basic_inventory"
        system_query_options:
          filter: "Id eq 33333 or Id eq 11111"

    - name: Retrieve inventory details of specified devices identified by IDs 11111 and 22222.
      dellemc_ome_device_facts:
        hostname:  "192.168.0.1"
        username: "username"
        password: "password"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_id:
            - 11111
            - 22222
            
    - name: Retrieve inventory details of specified devices identified by service tags MXL1234 and MXL4567.
      dellemc_ome_device_facts:
        hostname: "192.168.0.1"
        username: "username"
        password: "password"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_service_tag:
            - MXL1234
            - MXL4567

    - name: Retrieve details of specified inventory type of specified devices identified by ID and service tags.
      dellemc_ome_device_facts:
        hostname: "192.168.0.1"
        username: "username"
        password: "password"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_id:
            - 11111
          device_service_tag:
            - MXL1234
            - MXL4567
          inventory_type: "serverDeviceCards"

    - name: Retrieve subsystem health of specified devices identified by service tags.
      dellemc_ome_device_facts:
        hostname: "192.168.0.1"
        username: "username"
        password: "password"
        fact_subset: "subsystem_health"
        system_query_options:
          device_service_tag:
            - MXL1234
            - MXL4567
        
 
