---
- hosts: hosts
  connection: local
  name: Get LC job Status
  gather_facts: False

  tasks:
  - name: Get LC job Status
    dellemc_get_lc_job_status:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       job_id: "JID_123456789"
