---
- hosts: hosts
  connection: local
  name: Configure System lockdown mode
  gather_facts: False

  tasks:
  - name: Configure System lockdown mode
    dellemc_system_lockdown_mode:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       share_name: "{{ playbook_dir }}"
       lockdown_mode: "Disabled"

