name: DellEMC OpenManage Ansble Continuous Integration

on:
  push:
    branches: [ collections ]
  pull_request:
    branches: [ collections ]
  workflow_dispatch:

jobs:
  build:
    name: Build collection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible-version: [2.10.3]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install ansible (${{ matrix.ansible-version }})
        run: pip install ansible=="${{ matrix.ansible-version }}"

      - name: Build a collection tarball
        run: ansible-galaxy collection build --output-path "${GITHUB_WORKSPACE}/.cache/collection-tarballs"

      - name: Store migrated collection artifacts
        uses: actions/upload-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

  unit:
    name: Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.6]
        ansible-version: [stable-2.10, devel]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible (${{ matrix.ansible-version }}) version
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

      - name: Setup Unit test Pre-requisites
        run: |
          if [ -f /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/requirements.txt ]; then python -m pip install -r /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/requirements.txt; fi
          ansible-galaxy collection install .cache/collection-tarballs/*.tar.gz
          git clone https://github.com/ansible/ansible.git
          cp -rf ansible/test/units/compat /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/
          cp -rf ansible/test/units/modules/utils.py /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/plugins/modules/
          sed -i 's/units/ansible_collections.dellemc.openmanage.tests.unit/' /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage/tests/unit/plugins/modules/utils.py


      - name: Run Unit tests using ansible-test
        continue-on-error: true
        run: ansible-test units -v --color --python ${{ matrix.python-version }}
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage

#      - name: Run Unit tests using ansible-test
#        continue-on-error: true
#        run: ansible-test units -v --color --python ${{ matrix.python-version }} --coverage
#        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage
#
#      - name: Generate coverage report
#        run: ansible-test coverage xml -v --group-by command --group-by version
#        working-directory: ./home/runner/.ansible/collections/ansible_collections/dellemc/openmanage

      - name: Generate coverage report using pytest
        run: pytest -v --cov-config=tests/unit/plugins/.coveragerc --cov=plugins/ --cov-report=term-missing  --cov-fail-under=90 --cov-branch
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage


  sanity:
    name: Sanity Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        ansible-version: [stable-2.10, devel]

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install ansible (${{ matrix.ansible-version }}) version
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

      - name: Setup Sanity test Pre-requisites
        run: ansible-galaxy collection install .cache/collection-tarballs/*.tar.gz

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: /home/runner/.ansible/collections/ansible_collections/dellemc/openmanage